### ISSUE TITLE
Doesn't build against iOS SDK 2.20.0 and above

### ISSUE THREAD

**Issue by appden** [taplytics/taplytics-react-native#11]
The `registerPushNotificationsWithTypes:` method is being called (see [here](https://github.com/taplytics/taplytics-react-native/blob/master/ios/RNTaplyticsReact.m#L126)), but no longer exists since version 2.20.0 (see [here](https://github.com/taplytics/taplytics-ios-sdk/commit/4de9ea5f31f3c26a7055e2a1bf12cad478f555a4#diff-236289508bab04b4281496d4229edf27L205)).

**Comment by cdruxerman** [comment]
Hey @appden thank you for bringing this to our attention. I'll have our team look into it right away. I'll follow up with further details or if I need any additional context
