### ISSUE TITLE
Android/Java Override build error with RN v0.47+ 

### ISSUE THREAD

**Issue by niktonic21** [taplytics/taplytics-react-native#9]
I got an issue during the build:
_taplytics-react-native/android/src/main/java/com/taplytics/react/TaplyticsReactPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:taplytics-react-native:compileReleaseJavaWithJavac FAILED_

It look like general compatibility error with this lines of code. They should be removed.(or just @Override)

 @Override		
     public List<Class<? extends JavaScriptModule>> createJSModules() {		
       return Collections.emptyList();		
    }

Will there be an update at the earliest time? Thanks

**Comment by VicV** [comment]
We've fixed this a long time ago. Sorry to keep the issue open. Please upgrade to 1.0.12 or higher! 👍
